hello: ENC[AES256_GCM,data:rTe2YzEQYAOh/5/YxRchggTSPZyNpBsdtdE=,iv:vGB+Rp9ic1gnyK+FvQOoHsLnatlOGm7CbNvxBKm+904=,tag:taciY0kwXl0g7uaHWsSd8w==,type:str]
#ENC[AES256_GCM,data:3rnJR7iAvcui2i/PNqyzOcLIJjmBucw8,iv:I4eBSiFGgIaDt6BsF+n2L++KmwTCJj7PYtLyJnhflnY=,tag:2unvHQ4Jc1Sxfch1RAhHJA==,type:comment]
users:
    reedclanton:
        email: ENC[AES256_GCM,data:zMcuWS4Dw00idWmB6hSkiDfpUgrF,iv:s5I+S39PLFZsb9CGJXSVC1OmrNtzAc9EXzKp+jKms2Y=,tag:WMdr2iw3L9esK98a/ZkkWw==,type:str]
        pwd_hash: ENC[AES256_GCM,data:h8cMktbQDGFvq2ZJ7LtMVJOqCNQJaXvY+2NKnlY4jMejFJmBaXHuD/neyPAiqVxPdXR9/U12lvhPv0f+x301APAkm4r1ttLWVg==,iv:OPsPTdYqaI/n05tgqKzcni5Y/35GlFkFfth65GlMqt4=,tag:eblapqgvL6qVh6SVNBgDUw==,type:str]
#ENC[AES256_GCM,data:r0BMvh2ii16H8tYyEj+kpDQMzCXuY3M=,iv:NsWz2xqUnO+EFjCRUHn12+fxjGpr/Z/Q6TgpY+lUyXI=,tag:Ig5SHPTUIXsEj0+PoYezww==,type:comment]
app:
    element-desktop:
        message-key: ENC[AES256_GCM,data:0X6MJAmRo+o4xYmsT5B/XDL0Ae859jt/LfuodMm2JorvzkDxfmgmUuS2YvYPpzqs9pJsf+9DVYz8Yns=,iv:ZKzs1lb5pUUSIJd1AAFsIwGDoqKo/LoZriU3f6ig0lQ=,tag:1HdiB4L4KitDTl/A8ot+OQ==,type:str]
#ENC[AES256_GCM,data:KQ8PTadd/i0hoWIBsgf/V2pKme+0YIob2Pw=,iv:4nX1pQI3r5EhISXBZ3CmcmVTtqktk2/KoDU8cPiMi7c=,tag:nfG+TJaXULHwn3AznOzgAg==,type:comment]
file:
    kee-pass:
        reedclanton_psk: ENC[AES256_GCM,data:JDfBVw0G1vRg/A==,iv:K5tznPxrbXNr3OnuSqYWh4/reKxxbU/loQRYLyHvgYw=,tag:uIyQj7VXoa0NzA/5nV8Ccg==,type:str]
#ENC[AES256_GCM,data:YUsBOM0R7Np5zkFApAoXzw==,iv:ejWfDfLBbfyMuxmiYfGKSJjHOz5XIBAASvpcQWJInCI=,tag:crz2DVQW9nuu3a2/9/gXwQ==,type:comment]
wireless.env: ENC[AES256_GCM,data:NGk0aQB7sjti3NdmP5BJ2jrzqHArRbd9epy7s4UYVSaIH3vj2IlBtbJbDIMWRrOBAOc0Fvf2sGTRTvK5yAKAuv0FF3asH+JtY/cH0lIUsGhS0ewS37UF0qaKF5bWmfIkjSrYYiPr2pIfHHbd4n0jin3IZ5hBFAlTeYxbyRhVbBTwXmy2dKTErs37Rk75FEpZciVHzqrBsV8StAP9Xv20HPTton5ffAWNUzNdI0MTf+1PWlV3MR64R+2gbyc2sgnyQ1KfVLKEE/RtaDmCLyBWFBHh6zLuR75kEKJT104jLjyiCnrAVX52qz9Xc2mU6hnwbvuXW1uKSgs5kd8o1Hs3CbGMWjx9El2tLoXCv+BaOBWm1wAwC2AKt7/izorIfaQhiZeYUcsu0EKDX56wuc+2rmqeOaof7PfJWUEJoBFf2ln0wMoxc5tck7MoqJ/w6BRcBdRjSlrKQBdOiLuCtagoQ8lcWqSai6S5H/JtGj0bUdUVFzfNsFzk1te5xYgYGtETyxb7hYdjw6hS3lZak1ZMmexwrU6RrWdq+0Q9l4HkBrnS0BEvprNGKGRZSdtXg+w99oyFrYsy8a4dFS71W8kE240A2NgiqC5zEVfMULEaaEyxfM8agbMHSA91LRxVm0qDlg5dm6OKBLrjYPuHZDhnJ926BVG/C+aqiNWZbHOzo9SGIkBfrMFQYLUE2hVNCABkbHNuNLEX/d1i/ZjhknaAME3fOh0JWK1n22SAt0pKr+FPy61q6MY5oq8igUHzQlK+LJTuJbEn0cxCA6mrCZoSyQh82mMThqLD8vdvvIwal9B71xgqonMDsvH934Y4YpEtq2Nj9hyO1EnYK8GmkM0nQiMJtNMff1vVqBB60PDXK3d1t/osjgWT63z2jJFGb213omX+HWvi7G8aEiNjkra5JqTb0jNyO6hDi6KEt7H5xJOLP3QdqDzQirESUCRa8G8yT78Nj03a4hXHOP0dll5um7p8xBbaa8OLwsu1pPClv/oTeYTn6jJKcn9hjar1feN57YbJNmelTO5khTsKoyFMXF5qAYcQWm5VDV2b625XSgpUD7fDm66Tz9xgV9tn395OnnIjy1GH4gKax1lFKob9OwlWSoBdqViZRe67ftAjJYMH3c2WhmPrBPak0f+RixKXA/HzazRS+2axsKGS/gaP/PrYr1ASul091Uvcb0EHJCe0V125G7rhq/9Hf1ey/qBsURcnJXCIB4aZ0dJ4aG40DLzQTDajF9GoqV1vv2s+mcz3IjuS7x8JDPyFLCcTPjqLJuwrSehpm25ptSUn2k92vAj3b8BnC1MSxKeXMKBESoqYhFKTY25lbyjSGT349bb5Ss3gs+e6KOhTP+l6R8LBBRm7KFsPxDImeO77FaSdlfJR1F4YPPmLz5n3kuK2YavBGsqTwNWovfH9maZi+aL019W36zeualxRGzjp0NCavnXbQdrm,iv:M92yM76bw3DWt4Lu4FRUTo4AoszK724qqYsQG0l7xRg=,tag:K4BkPwzQ8zoTbcD6nHNLyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age154cs0j8qhequ64uujls9dnrefnjm2973hrsf4gxvfunyrtml84gspljeq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eDJTajY0dlViV3EyUDVZ
            ZzdGUzJzTXhVWDVqbVFydml3cTY3b1FsblY4ClpreHd2UWxidXhrcUxPL25kZ1Za
            VzRmWUd6TXpRRFIrQWsxUGd6ZXAvWkUKLS0tIHZ3M1BDZXZBZWRzSUV1R2RMWVRG
            VTFqS1EzZzZ2dE8zMzFlTVhmdWh1SlkKnZPxNLiRKqTzsa3Q2XQABSRtyL5inmMM
            fjR6CYFYuH/btwUA7n33TmqFGrnnq8lf+sjbe+bQpQxoU2Yrksc+SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T14:48:25Z"
    mac: ENC[AES256_GCM,data:cBhEkUpzz8CCbLpWjJcci2t6FgwYshpvYwrO2TwWqps5Ytr5cRUFbvhgHQAJwdO+JWkh6mgUH4MsDlXVopjmsxJM+NIrzQHHVgX8jY7dejbeLwzcbBKnZujWVQmDiZlZsDiLyPWHumKE5MXU61cVRpFf1aVmENU1u1o97juMuco=,iv:+Km3VpndBmNEKELnDVr0rZGcyYYeRPZD4dMSlkMI8dM=,tag:La0WfSbFA8sXj9yvSFcQ/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
